// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7gQsPoXj32fs7ZKMT_XXqC0gUykoqNRE',
    appId: '1:636586152857:web:085a0be0095a0261ed7908',
    messagingSenderId: '636586152857',
    projectId: 'moodyapb',
    authDomain: 'moodyapb.firebaseapp.com',
    storageBucket: 'moodyapb.appspot.com',
    measurementId: 'G-SQ878F0PEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4g2Kr6o-LtAt4D0FUqniqDG7wcALxVw4',
    appId: '1:636586152857:android:44e714810f8e9b52ed7908',
    messagingSenderId: '636586152857',
    projectId: 'moodyapb',
    storageBucket: 'moodyapb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDloRbrRm1o7tn-SSMmv3qM1k_qB3ktnkY',
    appId: '1:636586152857:ios:7ba9aa8f95eef7cded7908',
    messagingSenderId: '636586152857',
    projectId: 'moodyapb',
    storageBucket: 'moodyapb.appspot.com',
    iosClientId: '636586152857-7g143hmghrophbi3ggr3ot2j9ln3k5hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTubesSatu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDloRbrRm1o7tn-SSMmv3qM1k_qB3ktnkY',
    appId: '1:636586152857:ios:7ba9aa8f95eef7cded7908',
    messagingSenderId: '636586152857',
    projectId: 'moodyapb',
    storageBucket: 'moodyapb.appspot.com',
    iosClientId: '636586152857-7g143hmghrophbi3ggr3ot2j9ln3k5hm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTubesSatu',
  );
}
